### ISSUE TITLE
.donotbackup with open_basedir

### ISSUE THREAD

**Issue by Lukaaashek** [wp-media/backwpup#217]
**Describe the bug**
I get tens of error e-mails every day for each site because od .donotbackup file. The e-mails are full of this warnings (last e-mail 1406 lines of this warning):

Warning: file_exists(): open_basedir restriction in effect. File(/.donotbackup) is not within the allowed path(s): (/home/lukaaashek/public_html/:/tmp/)

And ends with error, that in the last one hour was no progress, interrupted by user etc.

I have shared hosting and disable access to another web folders by .htaccess line:

php_value open_basedir "/home/lukaaashek/public_html/:/tmp/"

The problem is, that script tries to access to root folder, but it's not allowed. Instead of continue it tries it again and again until job timeout.

**To Reproduce**
1. Add line php_value open_basedir "/root_folder/:/tmp/"
2. Run backup
3. See error / wait for e-mail

**Expected behavior**
Look for .donotbackup file only in WordPress root, or continue after unsuccessful search.

**Comment by Lukaaashek** [comment]
Problem is in file "backwpup/inc/class-jobtype-file.php", line 449.

![Image](https://github.com/user-attachments/assets/da1e954e-1959-41e1-8b5c-969733c75eb9)

When the $folder = "/home/lukaaashek/public_html/wp-content/", the $dir contains this array in foreach:

Array
(
    [0] => /home/lukaaashek/public_html/wp-content/plugins
    [1] => /home/lukaaashek/public_html/wp-content/upgrade-temp-backup
    [2] => /home/lukaaashek/public_html/wp-content/uploads
    [3] => /home/lukaaashek/public_html/wp-content/themes
    [4] => /home/lukaaashek/public_html/wp-content/upgrade
    [5] => /home/lukaaashek/public_html/wp-content/.
    [6] => /home/lukaaashek/public_html/wp-content/..
    [7] => /home/lukaaashek/public_html/wp-content/index.php
    [8] => /home/lukaaashek/public_html/wp-content/languages
    [9] => /home/lukaaashek/public_html/wp-content/wflogs
    **[10] =>** 
)

The last value returned is empty string. trailingslashit fill the slash, so then it looks for .donotbackup file in root folder, which isn't accessible.

I will make a PR, where I will add check, if folder is subfolder of the given $folder variable.

**Comment by Honemo** [comment]
Thank you again for your report and patch suggestion — we really appreciate it!

Before we proceed, could you help us with two things:

### 1. Can you test this alternative fix?
Instead of filtering based on path prefixes, we’re considering a simpler and safer approach: skip empty paths and check readability to avoid open_basedir warnings.

Could you try replacing your loop with this version and let us know if it solves the issue on your side?

```
foreach ( $dir as $file ) {
    $path = $file->getPathname();

    // Skip dot files and empty paths
    if ( $file->isDot() || empty( $path ) ) {
        continue;
    }

    // Avoid open_basedir issues by checking readability
    if ( ! is_readable( $path ) ) {
        continue;
    }
...
```

### 2. Help us understand the root cause
You mentioned that $dir contains an empty string. That’s likely wha's triggering the open_basedir warning.

- Do you know what folder or file might be generating this empty path?
- Is this something you can reproduce easily?
- If not, and you're comfortable with it, feel free to contact our support team and share temporary WP admin + FTP credentials — we can then reproduce and investigate the issue ourselves.

Looking forward to your feedback on the patch first — and thanks again for your help!

**Comment by Lukaaashek** [comment]
Hello @Honemo,

thanks for your comment.

1. The fix works very well. No problems since I patched the code with this alternative fix.
2. I have absolute no idea what can cause this. I tried to find it many ways and PHP functions. There is any hidden folder or symlink in the folder. The function generates list of correct paths and sometimes empty path, that after some processing leads to root folder.

**Comment by MathieuLamiot** [comment]
Fixed in 5.4

**Comment by MathieuLamiot** [comment]
@Lukaaashek Hi, do you have the possibility to check @danielhuesken's suggestion above? Thanks

**Comment by Lukaaashek** [comment]
@MathieuLamiot Thanks for it.

With getRealPath() it still throwing errors. The function getPathname() from [Honemo's alternative fix](https://github.com/wp-media/backwpup/issues/217#issuecomment-3145170954) returns another result than getRealPath(). Simple example from WordPress root:

```
$file = '';
$info = new SplFileInfo($file);
var_dump($info->getRealPath());
var_dump($info->getPathname());
```

Output:
```
string(27) "/home5/lukaaashek/public_html"
string(0) ""
```

The problem is with the realpath function. It makes root path from empty string.

When I use getPathname(), the empty string stays empty string. And the empty string is catched by both empty() and is_realpath() functions.

The most easiest solution for now is when I take actual version 5.5.0 code and add this to lines 459-460:

```
foreach ( $dir as $file ) {
	$path = $file->getPathname();
	if ( $file->isDot() || empty( $path ) ) {
		continue;
	}
```

**Comment by danielhuesken** [comment]
```
foreach ( $dir as $file ) {
				if ( $file->isDot() || ! $file->getPathname() ) {
					continue;
				}

				// Check readability before any filesystem operations.
				if ( ! $file->isReadable() ) {
					$job_object->log(
					// translators: %s: folder name.
					sprintf( __( 'Folder "%s" is not readable!', 'backwpup' ), $path ),
					E_USER_WARNING
					);
					continue;
				}

				$path = str_replace( '\\', '/', $file->getRealPath() );

				foreach ( $job_object->exclude_from_backup as $exclusion ) { // exclude files.
					$exclusion = trim( (string) $exclusion );
					if ( stripos( $path, $exclusion ) !== false && ! empty( $exclusion ) ) {
						continue 2;
					}
				}

				if ( $file->isDir() ) {
					if ( in_array( trailingslashit( $path ), $excludedirs, true ) ) {
						continue;
					}
					if ( file_exists( trailingslashit( $file->getPathname() ) . '.donotbackup' ) ) {
						continue;
					}
					$this->get_folder_list( $job_object, trailingslashit( $path ), $excludedirs, false );
				}

				if ( $first ) {
					$job_object->do_restart_time();
				}
			}
```
@Lukaaashek I made a change so that it is similar to that you suggested. Can you please try again.
